# Generated by Django 3.1.7 on 2021-07-19 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='suscriptor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo_pago', models.IntegerField(choices=[[0, 'DEBITO'], [1, 'CREDITO']])),
                ('monto_donacion', models.IntegerField(choices=[[0, 4990], [1, 5990], [2, 6990]])),
            ],
        ),
    ]
